/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.datamask.controller;import cn.zhuatech.datamask.service.DataMaskService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                              */
@RestController @RequestMapping("/api/datamask") @CrossOrigin public class DataMaskController{private final DataMaskService s;/**
                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                            */
public DataMaskController(DataMaskService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/preview") DataMaskService.Result preview(@Valid @RequestBody DataMaskService.Request r){return s.preview(r);}}
