/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.datamask;import cn.zhuatech.datamask.service.DataMaskService;import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;/**
                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                        */
class DataMaskServiceTests{private final DataMaskService s=new DataMaskService();/**
                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                         */
@Test void masksPhoneAndEmail(){var r=s.preview(new DataMaskService.Request(List.of(new DataMaskService.Field("phone","PHONE","13812345678"),new DataMaskService.Field("mail","EMAIL","a@zhuatech.cn"))));assertEquals(100.0,r.coverage());assertTrue(r.fields().get(0).maskedValue().contains("****"));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@Test void reportsUnknownType(){assertEquals(1,s.preview(new DataMaskService.Request(List.of(new DataMaskService.Field("x","UNKNOWN","v")))).unsupportedCount());}}
